### PR TITLE
Ensure artifacts are uploaded for main and PR

### PR DESCRIPTION
**Pull request by aangelisc**
- Add separate paths for PR and main

### CODE REVIEW

**Review by andresmgot — APPROVED** [review]
Aren't the paths already different? like [here](https://console.cloud.google.com/storage/browser/plugins-ci/drone/grafana/azure-data-explorer-datasource?authuser=0&project=grafanalabs-global&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)

**Comment by aangelisc** [comment]
> Aren't the paths already different? like [here](https://console.cloud.google.com/storage/browser/plugins-ci/drone/grafana/azure-data-explorer-datasource?authuser=0&project=grafanalabs-global&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)

Before this change the backend report would be written to `backend_coverage` and the frontend report to `coverage`. This would lead to the backend PR report being overwritten by the backend main report (as the main coverage test happens after the PR one) and the same effect for frontend. This change ensures that the main and PR reports do get written to separate folders 😊

**Comment by andresmgot** [comment]
ah, okay, got it, this has nothing to do with gcloud, files are uploaded to GH

**Comment by aangelisc** [comment]
I'd prefer to have both the PR and main coverage artifacts uploaded as I think it's useful for reference for the author 😊

**Pull request merged**
